In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("..//data//anthropometric_2003_2023.csv")
df.head(3)

,Year,Gender,Age,1.Body Weight (kg),2.Stature height (cm),3.The height of the root of the nose in standing (cm),4.Height of shoulders in standing position (cm),5.Height of the elbow in standing position (cm),6.The height of the tip of the 3rd finger in standing position (cm),7.Arm's reach in standing position (cm),...,16.Knee height in sitting position (cm),17.Arm's reach in sitting position (cm),18.The length of the forearm and hand at the elbow bend (cm),19.Thigh length in sitting position at knee bend (cm),20.Leg length when sitting forward (cm),21.Arm's reach in sitting position (cm),22.Palm width (cm),23.Palm length (cm),24.Foot width (cm),25.Foot lenght (cm)
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003.0,M,18,65,"173,5","168,0","144,0","105,0","67,0","220,0",...,"54,0","134,0","48,0","60,0","102,0","88,0","11,0","19,0","10,0","25,0"
2,2003.0,M,18,73,"170,0","168,0","152,0","118,0","71,0","224,0",...,"55,0","138,0","50,0","54,0","106,0","74,0","8,0","19,0","11,0","22,0"

In [ ]:
# --- Limpieza de datos

# Eliminar columnas
def drop_columns(data: pd.DataFrame, column_names: list) -> pd.DataFrame:
    return data[column_names]

# Eliminar nulos
def drop_nulls(data: pd.DataFrame) -> pd.DataFrame:
    return data.dropna()

# Resumen
def check_quality(data: pd.DataFrame):

    """Basic Quality Check. Returns DataFrame with columns, types 
    and unique, missing and duplicate elements plus their ratios.
    Complement/extension of .info() function."""

    n = len(data)

    summary = []
    for column in data:
        col_type = type(data[column].iloc[0])
        elements = data[column].count()
        unique = data[column].nunique(dropna = True)
        rate_unique = round(unique / n * 100, 2)
        missing = data[column].isna().sum() 
        rate_missing = round(missing / n * 100, 2)
        duplicated = data[column].duplicated().sum()
        
        summary.append((column, col_type, elements, unique, rate_unique, missing, rate_missing, duplicated))
    
    return pd.DataFrame(summary, columns = ['column', 'type', 'elements', 'unique', 'rate_unique', 'missing', 'rate_missing', 'duplicated'])


# Cambiar type
def change_type(data: pd.DataFrame, change_dict: dict) -> pd.DataFrame:

    """Changes column types to correct type indicated on dictionary values."""

    for column, correct_type in change_dict.items():
        
        if column not in data.columns:
            raise ValueError(f"Column {column} does not exist.")
        
        data[column] = data[column].astype(correct_type)

    return data

In [ ]:
columns = ['Year', 'Gender']

,column,type,elements,unique,rate_unique,missing,rate_missing,duplicated
0,Year,<class 'numpy.float64'>,4083,21,0.51,0,0.0,4062
1,Gender,<class 'str'>,4083,2,0.05,0,0.0,4081
2,Age,<class 'str'>,4083,97,2.38,0,0.0,3986
3,1.Body Weight (kg),<class 'str'>,4083,299,7.32,0,0.0,3784
4,2.Stature height (cm),<class 'str'>,4083,214,5.24,0,0.0,3869
5,3.The height of the root of the nose in standi...,<class 'str'>,4083,227,5.56,0,0.0,3856
6,4.Height of shoulders in standing position (cm),<class 'str'>,4083,223,5.46,0,0.0,3860
7,5.Height of the elbow in standing position (cm),<class 'str'>,4083,213,5.22,0,0.0,3870
8,6.The height of the tip of the 3rd finger in s...,<class 'str'>,4083,209,5.12,0,0.0,3874
9,7.Arm's reach in standing position (cm),<class 'str'>,4083,331,8.11,0,0.0,3752
10,8.The width of the shoulders (cm),<class 'str'>,4083,170,4.16,0,0.0,3913
11,9.Lateral chest diameter (cm),<class 'str'>,4083,203,4.97,0,0.0,3880
12,10.Arm's reach in standing position (cm),<class 'str'>,4083,206,5.05,0,0.0,3877
13,11.Arms spread in standing position (cm),<class 'str'>,4083,275,6.74,0,0.0,3808
14,12.Body height in sitting position (cm),<class 'str'>,4083,229,5.61,0,0.0,3854
15,13.Height of the root of the nose in a sitting...,<class 'str'>,4083,250,6.12,0,0.0,3833
16,14.Elbow height in sitting position (cm),<class 'str'>,4083,213,5.22,0,0.0,3870
17,15.Height of the upper arm when flexed at the ...,<class 'str'>,4083,175,4.29,0,0.0,3908
18,16.Knee height in sitting position (cm),<class 'str'>,4083,152,3.72,0,0.0,3931
19,17.Arm's reach in sitting position (cm),<class 'str'>,4083,296,7.25,0,0.0,3787
20,18.The length of the forearm and hand at the e...,<class 'str'>,4083,188,4.60,0,0.0,3895
21,19.Thigh length in sitting position at knee be...,<class 'str'>,4083,164,4.02,0,0.0,3919
22,20.Leg length when sitting forward (cm),<class 'str'>,4083,206,5.05,0,0.0,3877
23,21.Arm's reach in sitting position (cm),<class 'str'>,4083,197,4.82,0,0.0,3886
24,22.Palm width (cm),<class 'str'>,4083,88,2.16,0,0.0,3995
25,23.Palm length (cm),<class 'str'>,4083,118,2.89,0,0.0,3965
26,24.Foot width (cm),<class 'str'>,4083,79,1.93,0,0.0,4004
27,25.Foot lenght (cm),<class 'str'>,4083,124,3.04,0,0.0,3959